[BITS 16]
[ORG 0X7C00]

ENTRY_MENU: EQU 0X1000 ; ENDERECO DE ENTRADA

BOOT:
    ; DL SETADO PARA DRIVE DE BOOT
    MOV [BOOT_DRIVE], DL ; SALVA DRIVE DE BOOT EM DL

    XOR AX, AX ; LIMPEZA DE REGISTRADORES
    XOR BX, BX
    XOR CX, CX
    XOR DX, DX
    XOR SI, SI
    XOR DI, DI
    MOV DS, AX
    MOV ES, BX
    MOV SS, AX
    XOR SP, SP
    XOR BP, BP
    ; MOV CS, AX ; SEGMENTO DE CODIGO, SE RESETADO CODIGO NAO FUNCIONA

    CLD

START:
    MOV AH, 0 ; RESETAR SISTEMA DE DISCO
    MOV DL, 0X80 ; TANTO FLOPPY QUANTO HD (BIT 7 = 1)
    INT 0X13 ; SERVICOS DE DISCO DE BAIXO NIVEL

    MOV AH, 0X02 ; LEITURA DE SETORES
    MOV AL, 8 ; QTD DE SETORES (8 * 512B = 4096B = 4KiB)
    MOV CH, 0 ; CILINDRO 0
    MOV CL, 2 ; LER A PARTIR DO SETOR 2
    MOV DH, 0 ; CABECA 0
    MOV DL, [BOOT_DRIVE] ; DO DRIVE DE BOOT
    MOV BX, ENTRY_MENU ; OFFSET (ONDE COMECA O CODIGO, OU PARA ONDE LER)
    INT 0X13

    XOR AX, AX ; LIMPA NOVAMENTE REGISTRADORES
    XOR BX, BX
    XOR CX, CX
    XOR DX, DX
    XOR SI, SI
    XOR DI, DI
    MOV DS, AX
    MOV ES, BX
    MOV SS, AX
    XOR SP, SP
    XOR BP, BP

    JMP ENTRY_MENU

BOOT_DRIVE: DB 0

TIMES 510 - ($ - $$) DB 0

DW 0XAA55 ; ASSINATURA DE DRIVE BOOTAVEL
